<?php
namespace links\secciones;
use gamboamartin\errores\errores;
use gamboamartin\system\links_menu;
use stdClass;

class link_dp_pais extends links_menu {
    public stdClass $links;


    private function link_dp_pais_alta(): array|string
    {
        $dp_pais_alta = $this->dp_pais_alta();
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener link de dp_pais alta', data: $dp_pais_alta);
        }

        $dp_pais_alta.="&session_id=$this->session_id";
        return $dp_pais_alta;
    }

    protected function links(int $registro_id): stdClass|array
    {

        $links =  parent::links(registro_id: $registro_id); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al generar links', data: $links);
        }

        $dp_pais_alta = $this->link_dp_pais_alta();
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al generar link', data: $dp_pais_alta);
        }
        $this->links->dp_pais->nuevo_pais = $dp_pais_alta;

        return $links;
    }

    /**
     * Genera un link a empresa alta sin session_id
     * @return string Un link de tipo seccion org_empresa accion alta
     *
     */
    private function dp_pais_alta(): string
    {
        return "./index.php?seccion=dp_pais&accion=alta";
    }


}
