<?php
namespace gamboamartin\direccion_postal\models;
use base\orm\modelo;
use gamboamartin\errores\errores;
use PDO;
use stdClass;

class dp_colonia_postal extends modelo{
    public function __construct(PDO $link){
        $tabla = 'dp_colonia_postal';
        $columnas = array($tabla=>false,'dp_cp'=>$tabla,'dp_colonia'=>$tabla,'dp_municipio'=>'dp_cp',
            'dp_estado'=>'dp_municipio','dp_pais'=>'dp_estado');
        $campos_obligatorios[] = 'descripcion';

        parent::__construct(link: $link,tabla:  $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas);
    }

    public function alta_bd(): array|stdClass
    {
        if(!isset($this->registro['dp_cp_id'])){
            $dp_cp_id = (new dp_cp($this->link))->id_predeterminado();
            if(errores::$error){
                return $this->error->error(mensaje: 'Error al obtener cp predeterminado',data:  $dp_cp_id);

            }
            $this->registro['dp_cp_id'] = $dp_cp_id;

        }

        if(!isset($this->registro['dp_colonia_id'])){
            $dp_colonia_id = (new dp_colonia($this->link))->id_predeterminado();
            if(errores::$error){
                return $this->error->error(
                    mensaje: 'Error al obtener dp_colonia predeterminado',data:  $dp_colonia_id);

            }
            $this->registro['dp_colonia_id'] = $dp_colonia_id;

        }

        $r_alta_bd = parent::alta_bd(); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al  insertar municipio',data:  $r_alta_bd);

        }

        return $r_alta_bd;

    }
}