<?php
/**
 * @author Martin Gamboa Vazquez
 * @version 1.0.0
 * @created 2022-05-14
 * @final En proceso
 *
 */
namespace controllers;

use base\controller\salida_data;
use gamboamartin\errores\errores;
use gamboamartin\system\links_menu;
use gamboamartin\system\system;
use html\dp_cp_html;
use html\dp_municipio_html;
use html\dp_pais_html;
use models\dp_cp;
use PDO;
use stdClass;
use Throwable;

class controlador_dp_cp extends system {

    public function __construct(PDO $link, stdClass $paths_conf = new stdClass()){
        $modelo = new dp_cp(link: $link);
        $html = new dp_cp_html();
        $obj_link = new links_menu($this->registro_id);
        parent::__construct(html:$html, link: $link,modelo:  $modelo, obj_link: $obj_link, paths_conf: $paths_conf);

        $this->titulo_lista = 'Códigos Postáles';

    }

    public function alta(bool $header, bool $ws = false): array|string
    {
        $r_alta =  parent::alta(header: false); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar template', data: $r_alta,header: false,ws: false);
        }

        $this->inputs->select = new stdClass();

        $select = (new dp_cp_html())->select_dp_cp_id(id_selected:-1,link: $this->link);
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar select', data: $select,header: false,ws: false);
        }

        $this->inputs->select->dp_cp_id = $select;

        $select = (new dp_municipio_html())->select_dp_municipio_id(id_selected:-1,link: $this->link);
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar select', data: $select,header: false,ws: false);
        }

        $this->inputs->select->dp_municipio_id = $select;

        return $r_alta;
    }
    public function get_cp(bool $header, bool $ws = true): array|stdClass
    {

        $keys['dp_pais'] = array('id','descripcion','codigo','codigo_bis');
        $keys['dp_estado'] = array('id','descripcion','codigo','codigo_bis');
        $keys['dp_municipio'] = array('id','descripcion','codigo','codigo_bis');
        $keys['dp_cp'] = array('id','descripcion','codigo','codigo_bis');

        $filtro = $this->asigna_filtro_get($keys);
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar filtros',data:  $filtro,header: $header,ws: $ws);

        }


        $salida = (new salida_data())->salida_get(controler: $this,filtro:  $filtro,header:  $header,ws:  $ws);
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar salida',data:  $salida,header: $header,ws: $ws);

        }


        return $salida;


    }


}
